import { useState, useCallback } from 'react';

const LAYER_OPTIONS = [
  { id: 'Mean',   label: '5-Fold Mean Probability', suffix: 'SEA_Avg',  extra: '' },
  { id: 'Std',    label: 'Standard Deviation',       suffix: 'SEA_Std',  extra: '' },
  { id: 'Binary', label: 'Binary (prob ≥ 50%)',       suffix: 'SEA_Avg',  extra: 'binary' },
  { id: 'Pseudo', label: 'Pseudo-Labeling',           suffix: 'SEA_Pseu', extra: '' },
];

const SCALES = [30, 100, 250, 1000];

function generateScript({ country, gaulName, year, scale, folder, selectedLayers, projectId }) {
  const layerLines = selectedLayers.map(l => {
    const asset = `f'{ASSET_PREFIX}/{l.suffix}_{country.toLowerCase()}_{year}'`;
    const processing = l.extra === 'binary'
      ? `    img = ee.Image(${asset}).gte(50).selfMask().clip(geometry)`
      : `    img = ee.Image(${asset}).clip(geometry)`;
    return `
    # ── ${l.label}
    asset = f'{ASSET_PREFIX}/${l.suffix}_{country.lower()}_{year}'
    img   = ee.Image(asset)${l.extra === 'binary' ? '.gte(50).selfMask()' : ''}.clip(geometry)
    desc  = f'${l.suffix}_{country}_{year}'
    task  = ee.batch.Export.image.toDrive(
        image          = img,
        description    = desc,
        folder         = OUTPUT_FOLDER,
        fileNamePrefix = desc,
        region         = geometry,
        scale          = SCALE,
        crs            = 'EPSG:4326',
        maxPixels      = 1e13,
        fileFormat     = 'GeoTIFF',
    )
    task.start()
    print(f'  Started: {desc}  [{task.id}]')`;
  }).join('\n');

  return `#!/usr/bin/env python3
"""
SEA Rice Viewer — GEE Export Script
Country : ${country}
Year    : ${year}
Scale   : ${scale} m
Generated by sea-rice-viewer
"""
import ee

# ── Authenticate & initialise ─────────────────────────────────────────────────
ee.Authenticate()
ee.Initialize(project='${projectId || 'YOUR_GCP_PROJECT_ID'}')

# ── Configuration ─────────────────────────────────────────────────────────────
COUNTRY      = '${country}'
GAUL_NAME    = '${gaulName}'
YEAR         = ${year}
SCALE        = ${scale}        # metres per pixel
OUTPUT_FOLDER = '${folder}'
ASSET_PREFIX  = 'projects/tony-1122/assets/NIE/rice'

# ── Country boundary from FAO GAUL ────────────────────────────────────────────
fc = (ee.FeatureCollection('FAO/GAUL/2015/level0')
        .filter(ee.Filter.eq('ADM0_NAME', GAUL_NAME)))
geometry = fc.geometry()

print(f'Exporting {COUNTRY} ({YEAR}) at {SCALE} m ...')

${selectedLayers.map(l => `
# ── ${l.label}
asset = f'{ASSET_PREFIX}/${l.suffix}_' + COUNTRY.lower() + f'_{YEAR}'
img   = ee.Image(asset)${l.extra === 'binary' ? '.gte(50).selfMask()' : ''}.clip(geometry)
desc  = f'${l.suffix}_{country}_{year}'
task  = ee.batch.Export.image.toDrive(
    image          = img,
    description    = desc,
    folder         = OUTPUT_FOLDER,
    fileNamePrefix = desc,
    region         = geometry,
    scale          = SCALE,
    crs            = 'EPSG:4326',
    maxPixels      = 1e13,
    fileFormat     = 'GeoTIFF',
)
task.start()
print(f'  Started: {desc}  [{task.id}]')`).join('\n')}

print(f'\\nAll tasks submitted. Monitor at:')
print('  https://code.earthengine.google.com/tasks')
`;
}

export default function ExportModal({ country, gaulName, year, projectId, onClose }) {
  const [selected, setSelected]       = useState({ Mean: true, Std: false, Binary: false, Pseudo: false });
  const [scale, setScale]             = useState(30);
  const [folder, setFolder]           = useState('sea_rice_export');
  const [copied, setCopied]           = useState(false);

  const selectedLayers = LAYER_OPTIONS.filter(l => selected[l.id]);

  const script = generateScript({ country, gaulName, year, scale, folder, selectedLayers, projectId });

  const handleCopy = useCallback(() => {
    navigator.clipboard.writeText(script).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }, [script]);

  const handleDownload = useCallback(() => {
    const blob = new Blob([script], { type: 'text/x-python' });
    const url  = URL.createObjectURL(blob);
    const a    = document.createElement('a');
    a.href     = url;
    a.download = `sea_rice_export_${country.toLowerCase()}_${year}.py`;
    a.click();
    URL.revokeObjectURL(url);
  }, [script, country, year]);

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={e => e.stopPropagation()}>

        {/* Title bar */}
        <div className="modal-titlebar">
          <div className="modal-traffic">
            <span className="modal-dot red"   onClick={onClose} />
            <span className="modal-dot yellow" />
            <span className="modal-dot green"  />
          </div>
          <span className="modal-title">Export — {country} {year}</span>
        </div>

        <div className="modal-body">

          {/* Layers */}
          <div className="modal-section">
            <div className="modal-label">Layers to export</div>
            <div className="modal-grid2">
              {LAYER_OPTIONS.map(l => (
                <label key={l.id} className="checkbox-row">
                  <input type="checkbox" checked={!!selected[l.id]}
                    onChange={e => setSelected(s => ({ ...s, [l.id]: e.target.checked }))} />
                  <span className="checkbox-label">{l.label}</span>
                </label>
              ))}
            </div>
          </div>

          {/* Scale */}
          <div className="modal-section">
            <div className="modal-label">Resolution (m/px)</div>
            <div className="modal-scale-row">
              {SCALES.map(s => (
                <button key={s}
                  className={`scale-btn ${scale === s ? 'active' : ''}`}
                  onClick={() => setScale(s)}>
                  {s} m
                </button>
              ))}
            </div>
          </div>

          {/* Output folder */}
          <div className="modal-section">
            <div className="modal-label">Google Drive folder</div>
            <input className="input" value={folder}
              onChange={e => setFolder(e.target.value)}
              placeholder="sea_rice_export" />
          </div>

          {/* Script preview */}
          <div className="modal-section">
            <div className="modal-label">Generated Python script</div>
            <pre className="code-block">{script}</pre>
          </div>

        </div>

        {/* Footer */}
        <div className="modal-footer">
          <button className="btn btn-copy" onClick={handleCopy}>
            {copied ? '✓ Copied!' : 'Copy Script'}
          </button>
          <button className="btn btn-download-py" onClick={handleDownload}>
            ↓ Download .py
          </button>
        </div>

      </div>
    </div>
  );
}
